theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

#begin seo
title: Maker Faire Orlando
tagline: The Greatest Show (& Tell) on Earth!
description: Maker Faire Orlando is a community-organized, family-friendly celebration featuring local do-it-yourself science, art, rockets, robots, crafts, technology, music, hands-on-activities, and more. It’s an event where people show what they are making and share what they are learning. Maker Faire Orlando is produced by The Maker Effect Foundation.
logo: /assets/images/site-branding/mfo_two_line_border.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/site-branding/mfo_two_line_border.png

#end seo

collections:
   sponsors:
     output: false
     sort_by: sponsor-level



# set timezone
timezone: America/New_York

newsletter_url: http://eepurl.com/bpCB8T

event_date_descr: December 12th & 13th, 2020

event_location_descr: Central Florida Fairgrounds & Expo Halls

cta_nav_button_text: APPLY TO EXHIBIT!
cta_nav_button_url: /exhibit-at-maker-faire-Orlando

cta_footer_text: Subscribe for Info!
cta_footer_url: http://eepurl.com/bpCB8T

contact_email: makers@makerfaireorlando.com

event_year: 2020
event_name: Maker Faire Orlando

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'pets'
    template: 'pet'
    name: 'pet_name'
    dir: 'pets'
  - data: 'exhibits'
    template: 'exhibit'
    name: 'project_name'
    dir: 'exhibits'
